version: "3"

# Persistent volumes for Jenkins and Nginx
volumes:
  jenkins_home: {}
  jenkins_logs: {}
  nexus-data: {}
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}


networks:
  devops:
    driver: bridge
  gitlab-network:
    driver: bridge

services:
  jenkins:
    image: jenkins:latest
    build:
        context: jenkins
        dockerfile: Dockerfile
    container_name: jenkins_master
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"  
    ports:
      - "50000:50000"
      - "8080:8080"
    expose:
      - "50000"
      - "8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_logs:/var/log/jenkins
    networks:
      - devops

  nexus:
    image: sonatype/nexus
    container_name: nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081" 
    expose:
      - "8081"      
    networks:
      - devops   
      
  web:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab'
    restart: always
    hostname: 127.0.0.1
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:50080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    networks:
      - gitlab-network
    ports:
      - '50080:50080'
      - '50443:443'
      - '50022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

